name: Build
on:
    workflow_dispatch:

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - run: choco install pkgconfiglite
            - run: ./build-windows.cmd
    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - run: sh ./build-macos.sh
